### ISSUE TITLE
Version in whatsapp.desktop

### ISSUE THREAD

**Issue by nerijus** [cycool29/whatsapp-for-linux#2]
My whatsapp.desktop has:
```
[Desktop Entry]
Version=3.0
Name=WhatsApp
```
According to https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html:
```
Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.5. Note that the version field is not required to be present.
```
It should be something like 1.0 or 1.5. I'd suggest removing it at all, because most of the desktop files in my /usr/share/applications do not have Version.

**Comment by nerijus** [comment]
And as the script file has executable permissions now, `Exec=bash /usr/bin/whatsapp` can be changed to `Exec=/usr/bin/whatsapp`.

**Comment by cycool29** [comment]
> And as the script file has executable permissions now, `Exec=bash /usr/bin/whatsapp` can be changed to `Exec=/usr/bin/whatsapp`.

I leave it there so in case anything happened that the file is not executable, WhatsApp is still launchable from the menu.
At least, I don't see any negative effect of leaving the `bash` there.

**Comment by nerijus** [comment]
Version is fixed in the latest commit, thanks!
