### ISSUE TITLE
Update to electron 18.2.4 to fix debian buster and ubuntu bionic and older distro crash on launch

### ISSUE THREAD

**Issue by theofficialgman** [cycool29/whatsapp-for-linux#4]
**Describe the problem**:
Electron 18.0.0 to 18.2.3 pulled in a broken version of chromium causing it to crash on launch of other distros.
This has been fixed with 18.2.4 release a few minutes ago

Please update to this version as soon as possible. Nativefier should pull in the latest which would be 18.2.4 but just make sure it doesn't so when you are building.

**To Reproduce**:
Launch and crash on older linux releases

**Comment by cycool29** [comment]
Fixed in https://github.com/cycool29/whatsapp-for-linux/releases/tag/6.0.
